import { Product, Category, ServiceItem, Testimonial } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Sarees",
    slug: "sarees",
    image: "/images/categories/sarees.jpg",
    itemCount: "48+ Designs",
  },
  {
    id: "cat-2",
    name: "Blouses",
    slug: "blouses",
    image: "/images/categories/blouses.jpg",
    itemCount: "35+ Patterns",
  },
  {
    id: "cat-3",
    name: "Dresses & Kurtis",
    slug: "dresses",
    image: "/images/categories/dresses.jpg",
    itemCount: "28+ Styles",
  },
  {
    id: "cat-4",
    name: "Kids Wear",
    slug: "kids",
    image: "/images/categories/kids.jpg",
    itemCount: "22+ Outfits",
  },
  {
    id: "cat-5",
    name: "Tailoring Services",
    slug: "tailoring",
    image: "/images/categories/tailoring.jpg",
    itemCount: "Custom Fit",
  },
  {
    id: "cat-6",
    name: "Art & Crafts",
    slug: "crafts",
    image: "/images/categories/crafts.jpg",
    itemCount: "15+ Handmade",
  },
  {
    id: "cat-7",
    name: "Customized Gifts",
    slug: "gifts",
    image: "/images/categories/gifts.jpg",
    itemCount: "Personalized",
  },
  {
    id: "cat-8",
    name: "Festive Collection",
    slug: "festive",
    image: "/images/categories/festive.jpg",
    itemCount: "Diwali & Bridal",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Elegant Kanchipuram Saree",
    slug: "elegant-kanchipuram-saree",
    category: "sarees",
    categoryLabel: "Sarees",
    price: 1299,
    oldPrice: 1899,
    discount: 20,
    rating: 5.0,
    reviewsCount: 24,
    image: "/images/products/saree-01.jpg",
    description: "Handwoven pure silk Kanchipuram saree featuring intricate golden zari peacock motifs, rich contrasting burgundy pallu, and luxurious drape for weddings and festive milestones.",
    features: ["Pure Soft Silk Blend", "Rich Gold Zari Border", "Unstitched Blouse Piece Included", "Dry Clean Recommended"],
    isCustomizable: true,
    inStock: true,
  },
  {
    id: "prod-2",
    name: "Designer Blouse (Custom)",
    slug: "designer-blouse-custom",
    category: "blouses",
    categoryLabel: "Blouses",
    price: 899,
    oldPrice: 1299,
    discount: 30,
    rating: 5.0,
    reviewsCount: 38,
    image: "/images/products/blouse-01.jpg",
    description: "Artisanal hand-embroidered deep wine bridal blouse with heavy golden aari work, zardozi florals on neck and sleeves, and custom fitting tailored to your exact measurements.",
    features: ["Custom Tailoring Available", "Heavy Aari & Zardozi Work", "Padded with High Grade Cups", "Adjustable Back Latkan Tassels"],
    isCustomizable: true,
    inStock: true,
  },
  {
    id: "prod-3",
    name: "Kids Party Wear Dress",
    slug: "kids-party-wear-dress",
    category: "kids",
    categoryLabel: "Kids Wear",
    price: 799,
    oldPrice: 1199,
    discount: 35,
    rating: 4.9,
    reviewsCount: 19,
    image: "/images/products/kids-01.jpg",
    description: "Enchanting blush pink multi-layered tulle party frock with soft inner cotton lining for tender skin, delicate lace bodice, and luxury satin bow finish.",
    features: ["100% Breathable Cotton Lining", "Multi-Tiered Soft Tulle", "Gentle on Toddler Skin", "Custom Color Options"],
    isCustomizable: true,
    inStock: true,
  },
  {
    id: "prod-4",
    name: "Handmade Wall Décor",
    slug: "handmade-wall-decor",
    category: "crafts",
    categoryLabel: "Art & Crafts",
    price: 599,
    oldPrice: 899,
    discount: 33,
    rating: 4.8,
    reviewsCount: 14,
    image: "/images/products/decor-01.jpg",
    description: "Hand-sculpted and painted traditional terracotta mandala wall plate, decorated with royal peacock accents, rich burgundy highlights, and lustrous antique gold leafing.",
    features: ["Artisan Handcrafted", "Varnish Coated for Longevity", "Ready to Hang Hook Included", "Diameter: 12 Inches"],
    isCustomizable: false,
    inStock: true,
  },
  {
    id: "prod-5",
    name: "Handcrafted Potli Bag",
    slug: "handcrafted-potli-bag",
    category: "gifts",
    categoryLabel: "Customized Gifts",
    price: 499,
    oldPrice: 799,
    discount: 37,
    rating: 5.0,
    reviewsCount: 29,
    image: "/images/products/potli-01.jpg",
    description: "Royal burgundy velvet clutch potli pouch embellished with rich gold zardozi floral vines, heavy pearl tassel drawstrings, and spacious festive storage.",
    features: ["Plush Velvet Fabric", "Handcrafted Golden Latkans", "Spacious Interior Pouch", "Perfect for Return Gifts & Weddings"],
    isCustomizable: true,
    inStock: true,
  },
  {
    id: "prod-6",
    name: "Blush Pink Pleated Kurti Dress",
    slug: "blush-pink-pleated-kurti",
    category: "dresses",
    categoryLabel: "Dresses & Kurtis",
    price: 1149,
    oldPrice: 1699,
    discount: 32,
    rating: 4.9,
    reviewsCount: 21,
    image: "/images/products/dress-01.jpg",
    description: "Floor-length Anarkali flared kurti in soft blush pink georgette with shimmering gold foil neckline embroidery and ruffled sleeve cuffs.",
    features: ["Lightweight Breathable Georgette", "Fine Zari Yoke Work", "Flared 3.5m Ghera", "Stitched and Ready to Wear"],
    isCustomizable: true,
    inStock: true,
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: "srv-1",
    stepNumber: "01",
    title: "Tailoring for kids and womens",
    subtitle: "Perfect Fitting & Pattern Drafting",
    iconName: "Scissors",
    description: "Custom stitching for blouses, frocks, lehengas, kurtis, and gowns with millimeter precision measurement.",
  },
  {
    id: "srv-2",
    stepNumber: "02",
    title: "Customized Embroidery",
    subtitle: "Machine & Hand Needlework",
    iconName: "Sparkles",
    description: "Intricate floral monogramming, necklines, sleeves, and bridal borders with rich thread & beadwork.",
  },
  {
    id: "srv-3",
    stepNumber: "03",
    title: "Aari work for blouse and shirts",
    subtitle: "Authentic Zardozi & Maggam Art",
    iconName: "Shirt",
    description: "Specialized traditional Aari needle craftsmanship featuring stones, beads, pearls, and gold bullion wire.",
  },
  {
    id: "srv-4",
    stepNumber: "04",
    title: "Customized Arts and crafts",
    subtitle: "Decor & Bespoke Gifts",
    iconName: "Palette",
    description: "Personalized return gift hampers, hand-painted wall plates, festive hampers, and resin art.",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    name: "Priya K.",
    location: "Komarapalayam",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "Beautiful finishing and excellent service! The aari work on my bridal blouse was stunning. Highly recommended.",
    serviceUsed: "Bridal Aari Blouse",
  },
  {
    id: "test-2",
    name: "Divya R.",
    location: "Erode",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "Ordered a customized blouse and kids frock, and both were perfect! Loved the neat stitching and soft fabric.",
    serviceUsed: "Kids Party Wear & Blouse",
  },
  {
    id: "test-3",
    name: "Sneha M.",
    location: "Salem",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "Amazing handmade gifts. The wall decor plate and packaging was beautiful too! Fast delivery across Tamil Nadu.",
    serviceUsed: "Handmade Wall Décor",
  },
];

export const INSTAGRAM_POSTS = [
  { id: "ig-1", image: "/images/instagram/insta-1.jpg", caption: "Kanchipuram Silk Bridal Elegance ✨", likes: 248 },
  { id: "ig-2", image: "/images/instagram/insta-2.jpg", caption: "Heavy Zardozi & Aari Blouse Work 🪡", likes: 312 },
  { id: "ig-3", image: "/images/instagram/insta-3.jpg", caption: "Artisan Terracotta Peacock Wall Art 🦚", likes: 189 },
  { id: "ig-4", image: "/images/instagram/insta-4.jpg", caption: "Personalized Floral Gift Keepsake Box 🎁", likes: 220 },
  { id: "ig-5", image: "/images/instagram/insta-5.jpg", caption: "Festive Brass Diya Urli Decor 🪔", likes: 405 },
  { id: "ig-6", image: "/images/instagram/insta-6.jpg", caption: "Artisanal Tailoring Tools & Pure Threads ✂️", likes: 176 },
  { id: "ig-7", image: "/images/instagram/insta-7.jpg", caption: "Blush Pink Tulle Kids Dream Dress 🎀", likes: 350 },
];
